spring.application.name=1_SpringBoot

#oracle 연결(원래는 mybatis config에 들어갈 내용들이었음)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=SPRINGBOOT
spring.datasource.password=SPRINGBOOT

#타임리프 설정
spring.thymeleaf.cache=false

#Mybatis 설정
#mybatis.mapper-locations=classpath:mappers/member-mapper.xml, classpath:mappers/board-mapper.xml
#mapper가 갈수록 늘어날 수 있기 때문에 하위에 있는 모든 xml을 선택
mybatis.mapper-locations=classpath:mappers/**.xml 
#setter의 이름과 select후 rset의 컬럼명이 _ 하나 차이 && 낙타봉 표기법이 잘 지켜졌을 때 사용하는 설정
mybatis.configuration.map-underscore-to-camel-case=true
#alias 설정을 통하여 클래스 이름만 쓸 수 있도록 해줌
#mybatis.type-aliases-package=kh.springboot.member.model.vo, kh.spring.board.model.vo 
mybatis.type-aliases-package=kh.springboot.*.model.vo
#jdbc가 null을 인지하게
mybatis.configuration.jdbc-type-for-null=null